global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "my-app-actuator"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 30s
    static_configs:
    - targets: ["host.docker.internal:8080"]

